[pytest]
DJANGO_SETTINGS_MODULE = config.settings.base
python_files = tests.py test_*.py *_tests.py
addopts = --nomigrations --disable-warnings --strict-markers
markers =
    geo: Pruebas espaciales y de trigonometría PostGIS
    integration: Pruebas de conexión a GraphQL o Firebase
