# Generated by Django 4.2.30 on 2026-05-30 16:59

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoExterno",
            fields=[
                (
                    "codigo_sku",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "precio_referencial",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("stock_global", models.IntegerField()),
            ],
            options={
                "db_table": "venado_erp_productos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RutaAsignada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_sucursal", models.CharField(max_length=255)),
                (
                    "ubicacion_objetivo",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Coordenada GPS del punto de venta", srid=4326
                    ),
                ),
                (
                    "radio_tolerancia_metros",
                    models.FloatField(
                        default=50.0,
                        help_text="Radio geográfico permitido para que un check-in sea válido",
                    ),
                ),
                ("fecha_asignacion", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "logistica_ruta_asignada",
            },
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("PING", "Background Ping"),
                            ("CHECKIN", "Llegada a Sucursal"),
                            ("CHECKOUT", "Salida de Sucursal"),
                        ],
                        default="PING",
                        max_length=20,
                    ),
                ),
                (
                    "ubicacion_actual",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Coordenada GPS exacta del evento emitido por el móvil",
                        srid=4326,
                    ),
                ),
                (
                    "velocidad_kmh",
                    models.FloatField(
                        default=0.0,
                        help_text="Velocidad reportada por el hardware GPS (para anti-spoofing)",
                    ),
                ),
                ("bateria_porcentaje", models.IntegerField(default=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "es_mock_location",
                    models.BooleanField(
                        default=False,
                        help_text="True si el SO móvil detectó que la ubicación fue simulada",
                    ),
                ),
                (
                    "reponedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ruta_asociada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistica.rutaasignada",
                    ),
                ),
            ],
            options={
                "db_table": "logistica_tracking_event",
            },
        ),
        migrations.CreateModel(
            name="FormularioDinamico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_formulario",
                    models.CharField(
                        help_text="Contexto de llenado, Ej: 'Fiebre_Precios', 'Stock_Out', 'Quiebre_Gondola'",
                        max_length=100,
                    ),
                ),
                (
                    "datos_extra",
                    models.JSONField(
                        default=dict,
                        help_text="Absorbe diccionarios/listas de tamaño ilimitado sin necesidad de alterar el modelo SQL",
                    ),
                ),
                (
                    "foto_evidencia",
                    models.ImageField(
                        blank=True, null=True, upload_to="evidencias/%Y/%m/%d/"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "tracking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistica.trackingevent",
                    ),
                ),
            ],
            options={
                "db_table": "logistica_formulario_dinamico",
            },
        ),
        migrations.AddIndex(
            model_name="trackingevent",
            index=models.Index(
                fields=["timestamp", "reponedor"], name="logistica_t_timesta_72ad7d_idx"
            ),
        ),
    ]
