# Generated by Django 4.2.30 on 2026-05-30 22:09

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoExterno",
            fields=[
                (
                    "codigo_sku",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "precio_referencial",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("stock_global", models.IntegerField()),
            ],
            options={
                "db_table": "venado_erp_productos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClientType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MAYORISTA", "MAYORISTA"),
                            ("MINORISTA", "MINORISTA"),
                            ("DETALLISTA", "DETALLISTA"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("min_purchase_bs", models.IntegerField()),
                ("avg_visit_minutes", models.SmallIntegerField()),
                ("attention_profile", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "client_types",
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("zone", models.CharField(blank=True, max_length=80, null=True)),
                ("city", models.CharField(default="La Paz", max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "markets",
            },
        ),
        migrations.CreateModel(
            name="PDV",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("client_code", models.CharField(max_length=20)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("visit_mon", models.BooleanField(default=False)),
                ("visit_tue", models.BooleanField(default=False)),
                ("visit_wed", models.BooleanField(default=False)),
                ("visit_thu", models.BooleanField(default=False)),
                ("visit_fri", models.BooleanField(default=False)),
                ("visit_sat", models.BooleanField(default=False)),
                ("visit_minutes_estimated", models.SmallIntegerField(default=20)),
                ("weekly_frequency", models.SmallIntegerField(default=1)),
                ("monthly_frequency", models.SmallIntegerField(default=4)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdvs",
                        to="logistica.clienttype",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdvs",
                        to="logistica.market",
                    ),
                ),
            ],
            options={
                "db_table": "pdvs",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("route_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_pdvs", models.SmallIntegerField(default=0)),
                ("total_estimated_minutes", models.SmallIntegerField(default=0)),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
                ),
                ("total_real_minutes", models.SmallIntegerField(blank=True, null=True)),
                (
                    "total_real_distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "replenisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "routes",
                "unique_together": {("replenisher", "route_date")},
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stop_order", models.SmallIntegerField()),
                ("estimated_minutes", models.SmallIntegerField()),
                (
                    "distance_from_prev_km",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("real_minutes", models.SmallIntegerField(blank=True, null=True)),
                (
                    "arrival_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "distance_to_pdv_m",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                (
                    "pdv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logistica.pdv"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="logistica.route",
                    ),
                ),
            ],
            options={
                "db_table": "route_stops",
                "unique_together": {("route", "stop_order")},
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("visit_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_minutes", models.SmallIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pdv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logistica.pdv"
                    ),
                ),
                (
                    "replenisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visits",
                        to="logistica.routestop",
                    ),
                ),
            ],
            options={
                "db_table": "visits",
            },
        ),
        migrations.CreateModel(
            name="RestockRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=120)),
                ("quantity_requested", models.SmallIntegerField()),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("fulfilled", "Fulfilled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("photo_url", models.TextField(blank=True, null=True)),
                ("supervisor_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pdv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logistica.pdv"
                    ),
                ),
                (
                    "replenisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restock_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_restocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistica.visit",
                    ),
                ),
            ],
            options={
                "db_table": "restock_requests",
            },
        ),
        migrations.CreateModel(
            name="ProductIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=120)),
                ("quantity", models.SmallIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("expired", "Expired"),
                            ("damaged", "Damaged"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("photo_url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pdv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logistica.pdv"
                    ),
                ),
                (
                    "replenisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistica.visit",
                    ),
                ),
            ],
            options={
                "db_table": "product_issues",
            },
        ),
        migrations.CreateModel(
            name="FormularioDinamico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_formulario",
                    models.CharField(
                        help_text="Contexto de llenado, Ej: 'Fiebre_Precios', 'Stock_Out', 'Quiebre_Gondola'",
                        max_length=100,
                    ),
                ),
                (
                    "datos_extra",
                    models.JSONField(
                        default=dict,
                        help_text="Absorbe diccionarios/listas de tamaño ilimitado sin necesidad de alterar el modelo SQL",
                    ),
                ),
                (
                    "foto_evidencia",
                    models.ImageField(
                        blank=True, null=True, upload_to="evidencias/%Y/%m/%d/"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formularios_dinamicos",
                        to="logistica.visit",
                    ),
                ),
            ],
            options={
                "db_table": "logistica_formulario_dinamico",
            },
        ),
        migrations.AddIndex(
            model_name="pdv",
            index=models.Index(fields=["is_active"], name="pdvs_is_acti_4a7d4d_idx"),
        ),
    ]
