# Generated by Django 4.2.30 on 2026-05-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistica", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariodinamico",
            name="foto_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formulariodinamico",
            name="foto_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formulariodinamico",
            name="notas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formulariodinamico",
            name="sesion_iniciada_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
